package com.example.mnewsapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFD940c5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD7F1)
val onPrimaryContainerLight = Color(0xFF67355D)
val secondaryLight = Color(0xFF196585)
val onSecondaryLight = Color(0xFF3EC6FF)
val secondaryContainerLight = Color(0xFFC2E8FF)
val onSecondaryContainerLight = Color(0xFF004D67)
val tertiaryLight = Color(0xFF000000)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDBCF)
val onTertiaryContainerLight = Color(0xFF663C2C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF7F9)
val onBackgroundLight = Color(0xFF201A1E)
val surfaceLight = Color(0xFFFFF7F9)
val onSurfaceLight = Color(0xFF201A1E)
val surfaceVariantLight = Color(0xFFEFDEE6)
val onSurfaceVariantLight = Color(0xFF4E444A)
val outlineLight = Color(0xFF80747B)
val outlineVariantLight = Color(0xFFD2C2CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362E33)
val inverseOnSurfaceLight = Color(0xFFFBEDF3)
val inversePrimaryLight = Color(0xFFF4B2E2)
val surfaceDimLight = Color(0xFFE3D7DC)
val surfaceBrightLight = Color(0xFFFFF7F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFEF0F6)
val surfaceContainerLight = Color(0xFFF8EAF0)
val surfaceContainerHighLight = Color(0xFFF2E5EB)
val surfaceContainerHighestLight = Color(0xFFECDFE5)

val customTitleColor = Color(0xFF464646)
val secondTitleColor = Color(0xFF707070)
val thirdTitleColor = Color(0xFFDFDFDF)

val BlueGray = Color(0xFFA0A3BD)



val primaryDark = Color(0xFFD940c5)
val onPrimaryDark = Color(0xFF4E1E45)
val primaryContainerDark = Color(0xFF67355D)
val onPrimaryContainerDark = Color(0xFFFFD7F1)
val secondaryDark = Color(0xFF8ECFF2)
val onSecondaryDark = Color(0xFF3EC6FF)
val secondaryContainerDark = Color(0xFF004D67)
val onSecondaryContainerDark = Color(0xFFC2E8FF)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFF4C2618)
val tertiaryContainerDark = Color(0xFF663C2C)
val onTertiaryContainerDark = Color(0xFFFFDBCF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF181216)
val onBackgroundDark = Color(0xFFECDFE5)
val surfaceDark = Color(0xFF181216)
val onSurfaceDark = Color(0xFFECDFE5)
val surfaceVariantDark = Color(0xFF4E444A)
val onSurfaceVariantDark = Color(0xFFD2C2CA)
val outlineDark = Color(0xFF9B8D95)
val outlineVariantDark = Color(0xFF4E444A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFECDFE5)
val inverseOnSurfaceDark = Color(0xFF362E33)
val inversePrimaryDark = Color(0xFF824C76)
val surfaceDimDark = Color(0xFF181216)
val surfaceBrightDark = Color(0xFF3F373C)
val surfaceContainerLowestDark = Color(0xFF120C10)
val surfaceContainerLowDark = Color(0xFF201A1E)
val surfaceContainerDark = Color(0xFF241E22)
val surfaceContainerHighDark = Color(0xFF2F282C)
val surfaceContainerHighestDark = Color(0xFF3A3337)

